version: "3.5"

services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    volumes:
      - /media/pi/ExtDrive/storage/Services/Kavita/config:/kavita/config
      - /media/pi/ExtDrive/storage/Media/Literature:/manga
    ports:
      - 8686:5000
    restart: no
