version: "2.1"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000 #to find use: $ id $USER
      - PGID=1000 #to find use: $ id $USER
      - TZ=America/Sao_Paulo
    volumes:
      - /path/to/data:/config
      - /path/to/tvseries:/tv
      - /path/to/downloadclient-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped