services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    network_mode: host
    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      - ./data:/data
      - ./config:/config
