services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    network_mode: host
    volumes:
      - /mnt/storage/SERVICES/Caddy/conf:/etc/caddy
      - /mnt/storage/SERVICES/Caddy/site:/srv
      - /mnt/storage/SERVICES/Caddy/data:/data
      - /mnt/storage/SERVICES/Caddy/config:/config
