version: "2.1"

services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - SUBDOMAINS=jellyfin,ssh
      - TOKEN=token
      - LOG_FILE=false
    volumes:
      - /path/to/appdata/config:/config
    restart: unless-stopped