services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /media/pi/ExtDrive/storage/Media/Literature/Audiobooks:/audiobooks
      - /media/pi/ExtDrive/storage/Media/Podcasts:/podcasts
      - /media/pi/ExtDrive/storage/Services/Audiobookshelf/config:/config
      - /media/pi/ExtDrive/storage/Services/Audiobookshelf/metadata:/metadata
    restart: no
