services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /mnt/storage/MEDIA/Literature/Audiobooks:/audiobooks
      - /mnt/storage/MEDIA/Podcasts:/podcasts
      - /mnt/storage/SERVICES/Audiobookshelf/config:/config
      - /mnt/storage/SERVICES/Audiobookshelf/metadata:/metadata
    restart: no
