services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /media/pi/ExtDrive/storage/Services/Komga/config
        target: /config
      - type: bind
        source: /media/pi/ExtDrive/storage/Media/Literature
        target: /data
    ports:
      - 25600:25600
    user: "1000:1000"
    environment:
      - TZ=America/Sao_Paulo
      - JAVA_TOOL_OPTIONS=-Xmx2g
    restart: no
