services:
  gotify:
    image: gotify/server-arm64
    container_name: gotify
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/storage/SERVICES/Gotify/data:/app/data
    ports:
      - 7561:80
    restart: no
