version: "2.1"

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /path/to/appdata:/config
      - /path/to/data:/data
    ports:
      - 7562:443
    restart: no