services:
  nextcloud:
    image: linuxserver/nextcloud:arm64v8-27.0.1
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /media/pi/ExtDrive/storage/Services/Nextcloud/config:/config
      - /media/pi/ExtDrive/storage/Services/Nextcloud/data:/data
      - /media/pi/ExtDrive/storage/Media:/media
    ports:
      - 7562:443
    restart: no
