version: "2.1"

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /media/pi/Seagate Basic/Services/Nextcloud/config:/config
      - /media/pi/Seagate Basic/Services/Nextcloud/data:/data
    ports:
      - 7562:443
    restart: no