version: "2.1"

# Docker image update and recreation of container alone won't update nextcloud version.
# In order to update nextcloud version, you have two options,
# firstly make sure you are using the latest docker image, then either:
# 1. Perform the in app gui update.
# 2. Use the CLI version by running docker exec -it nextcloud updater.phar

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /path/to/appdata:/config
      - /path/to/data:/data
    ports:
      - 443:443
    restart: unless-stopped