version: "2.1"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/pi/Projects/Radarr/config:/config
      - /media/pi/Seagate Basic/Media:/data
    ports:
      - 7878:7878
    restart: unless-stopped
