services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      - UID=1000
      - GID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /media/pi/ExtDrive/storage/Services/Homarr/configs:/app/data/configs
      - /media/pi/ExtDrive/storage/Services/Homarr/data:/data
      - /media/pi/ExtDrive/storage/Services/Homarr/icons:/app/public/icons
    ports:
      - 7575:7575
    restart: no
