version: "3"

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    volumes:
      - /path/to/configs:/app/data/configs
      - /path/to/icons:/app/public/icons
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 7575:7575
    restart: unless-stopped