services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      - UID=1000
      - GID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /path/to/configs:/app/data/configs
      - /path/to/data:/data
      - /path/to/icons:/app/public/icons
    ports:
      - 7575:7575
    restart: no
