version: "3.5"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - /home/pi/Projects/Jellyfin/config:/config
      - /home/pi/Projects/Jellyfin/cache:/cache
      - /media/pi/Seagate Basic/Media:/media
    restart: "unless-stopped"
