services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/storage/SERVICES/Jellyfin/config:/config
      - /mnt/storage/SERVICES/Jellyfin/cache:/cache
      - /mnt/storage/MEDIA:/media
    restart: no
