services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /media/pi/ExtDrive/storage/Services/Jellyfin/config:/config
      - /media/pi/ExtDrive/storage/Services/Jellyfin/cache:/cache
      - /media/pi/ExtDrive/storage/Media:/media
    restart: no
