version: "3.5"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - /path/to/config:/config #EDIT
      - /path/to/cache:/cache   #EDIT
      - /path/to/media:/media   #EDIT
    restart: "unless-stopped"