services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest-alpine
    ports:
      - '5006:5006'
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /media/pi/ExtDrive/storage/Services/ActualBudget/data:/data
    restart: no
