volumes:
  data:
  extensions:

services:

  freshrss:
    image: freshrss/freshrss:edge
    container_name: freshrss
    platform: linux/arm/v7
    hostname: freshrss
    restart: no
    logging:
      options:
        max-size: 10m
    volumes:
      - /mnt/storage/SERVICES/Freshrss/data:/var/www/FreshRSS/data
      - /mnt/storage/SERVICES/Freshrss/extensions:/var/www/FreshRSS/extensions
    ports:
      - 8650:80
    environment:
      TZ: America/Sao_Paulo
      FRESHRSS_ENV: development
      CRON_MIN: '1'
