services:

  server:
    image: szurubooru/server:latest
    depends_on:
      - sql
    environment:
      POSTGRES_HOST: sql
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      THREADS:
    volumes:
      - "${SZURU_MOUNT_DATA}:/data"
      - "${SZURU_MOUNT_CONFIG}/config.yaml:/opt/app/config.yaml"

  client:
    image: szurubooru/client:latest
    depends_on:
      - server
    environment:
      BACKEND_HOST: server
      BASE_URL:
    volumes:
      - "${MOUNT_DATA}:/data:ro"
    ports:
      - "${PORT}:80"

  sql:
    image: postgres:11-alpine
    restart: no
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - "${MOUNT_SQL}:/var/lib/postgresql/data"
