services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    environment:
      - BASE_URL=https://your.domain.here/location
      - INSTANCE_NAME=searxngpi
    volumes:
      - /home/pi/Projects/Searx/searxng:/etc/searxng
    ports:
      - 7560:8080
    restart: no
