services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    environment:
      - BASE_URL=https://vinesma.duckdns.org/searx/
      - INSTANCE_NAME=searxngpi
    volumes:
      - /home/pi/Services/Searx/searxng:/etc/searxng
    ports:
      - 7560:8080
    restart: no
