version: "2.1"

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    environment:
      - BASE_URL=https://your.domain.here/location
      - INSTANCE_NAME=searxngpi
    volumes:
      - /path/to/data:/etc/searxng
    ports:
      - 7560:8080
    restart: on-failure